version: '3'

services:
  active-mq-custom:
    image: rmohr/activemq:5.14.2-alpine
    restart: always
    ports:
      - 61616:61616
      - 8161:8161
    networks:
      - common-network

networks:
  common-network:
    external: true