# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres-db-9.5.25:    
    image: postgres:9.5.25-alpine
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres-database-schema.sql:/docker-entrypoint-initdb.d/database_schema.sql
    networks:
      - common-network

networks:
    common-network:
      external: true

#The PostgreSQL database
#Server : localhost
#User/Pass : root/root
#Database : root